### ISSUE TITLE
floor 56画像がない

### ISSUE THREAD

**Issue by tsukimizake** [kojim/SlayTheReport#20]
画像欠けてる問題はほぼ解決したっぽいけれど最終フロアだけ欠けてるのがちょっと残念
キャラごとに表示画像変えられるとオシャレだけど専用の実装が要りそう

**Comment by kojim** [comment]
どうやらfloor56が表示されるのは勝利時のみのようなので、
キャラごとの勝利画像(ビーム吐いて心臓貫いているディレクトくんとか)を表示するのが妥当な気がします。
(今思いつきました)

ボスまでワープするイベント踏むと、階数がズレるのをどうしようかと悩んでいたのですが、
path_per_floor の4番目のnullのフロアに勝利画像配置するという実装が素直そうです。
(これも今思いつきました)

ちょっと前までfloor56はゴミなので消すか？
とも思っていたのですが、floor56にプレイ総評書いている人がいたので、
そういう用途に使ってもらうのが良いかなと、今は残す方向で考えています。
心臓戦のところにプレイ総評書くのもなんか座りが悪いですしね。

**Comment by kojim** [comment]
実装しました。
が！画像が横長なせいでなんかしょぼい感じになってしまっている。
せっかくの余韻が台無しだよ。
ということでこのIssueクローズするのはその問題クリアしてからかなぁ。
